FROM alpine:3.18 as builder

ENV VERSION '0.16.2'

RUN set -ex \
    && apk add --no-cache curl tar \
    && curl -fSL https://github.com/k0kubun/sqldef/releases/download/v$VERSION/mysqldef_linux_amd64.tar.gz -o mysqldef.tar.gz \
    && tar -zxf mysqldef.tar.gz

FROM alpine:3.18
COPY --from=builder /mysqldef /usr/local/bin/mysqldef
CMD ["mysqldef"]
